### ISSUE TITLE
Map legend: text wraps and triggers scroll in overlay [Chrome Windows]

### ISSUE THREAD

**Issue by jorupp** [GUI/covid-vaccine-spotter#106]
I see this today in Chrome 89.0.4389.90 on Windows:
![image](https://user-images.githubusercontent.com/3874909/112839868-4c875900-9064-11eb-8cc3-9b8dd8922a19.png)

I'm guessing the icons slightly increased in size (or spacing) in https://github.com/GUI/covid-vaccine-spotter/pull/104.

**Comment by jorupp** [comment]
Eye-balling it, changing `#legend`'s `height` from `64px` to `67px` should be enough to fix it.  Alternatively, `overflow: hidden` should work too.

**Comment by clottman** [comment]
I can create a PR for this. Will give `#legend` a height of `min-content`, with a fallback in pixels to keep it doing something sensible in IE11.
