### ISSUE TITLE
Website blocked

### ISSUE THREAD

**Issue by H4CKL0RD** [GUI/covid-vaccine-spotter#120]
The website is forbidden error 403, if I cannot use this website to crawl, which other ones can I use that have multiple locations?

**Comment by GUI** [comment]
@H4CKL0RD: Can you provide more details? Where are you seeing 403 forbidden errors? On the web page in a browser, or are you trying to crawl with some other tools? I'm not aware of anything that would lead to 403 errors, but it's possible CloudFlare might be doing something. If you're looking to crawl the site, have you seen the [APIs](https://www.vaccinespotter.org/api/)?

**Comment by H4CKL0RD** [comment]
Ok I havent seen the api's since this is mostly what i was trying to do
(its in python, sharing my code here)

`from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
state = input("What state are you in(reply with state abv): ")
zipcode = input("What is your zip code?: ")
VaccineType = input("Do you want to choose a type of vaccine? If so tell the type of vaccine(Johnsen+Johnsen(just type jj), moderna, and pfizer)if not type none: ")

if VaccineType == "jj":
    url =f"https://www.vaccinespotter.org/{state}/?zip={zipcode}&vaccine_type=jj&radius=100"
if VaccineType == "pfizer":
    url = f"https://www.vaccinespotter.org/{state}/?zip={zipcode}&vaccine_type=pfizer&radius=100"
if VaccineType == "moderna":
    url = f"https://www.vaccinespotter.org/{state}/?zip={zipcode}&vaccine_type=moderna&radius=100"
else:
    url = f"https://www.vaccinespotter.org/{state}X/?zip={zipcode}&radius=100&include_all=true"


print (url)

uClient = uReq(url)
page_html = uClient.read(url)

uClient.close()

page_soup = soup(page_html, "html.parser")

page_soup.h1`

**Comment by H4CKL0RD** [comment]
I just had a test for finding the header and i got this error `raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`

**Comment by H4CKL0RD** [comment]
hello?? @GUI

**Comment by H4CKL0RD** [comment]
Nevermind, i was using urllib instead of requests. My bad.
