### ISSUE TITLE
Show number pad on zip code field on mobile

### ISSUE THREAD

**Issue by blanchardjeremy** [GUI/covid-vaccine-spotter#123]
Super small thing: it'd be nice if the zip code field was a number field. So that on mobile the num pad automatically shows up. 

Thanks for coding this!

**Comment by GUI** [comment]
Great, suggestion! This always drives me crazy myself when sites don't do this, but I obviously hadn't done it for my own site. :) But should be fixed now. Thank you!

**Comment by blanchardjeremy** [comment]
Thanks!!
