### ISSUE TITLE
security issue, need to talk asap

### ISSUE THREAD

**Issue by princezuda** [GUI/covid-vaccine-spotter#129]
I don't want to go into details, but I tweeted you on Twitter. There is a severe security issue that needs to be addressed. I would love to help you with it, but this isn't something I can pull and fix. It's more complicated.

**Comment by princezuda** [comment]
After this was peer reviewed by other researchers it has been deemd not a problem.

**Comment by paf0186** [comment]
Since this was not an issue, would you mind describing the possible concern?

**Comment by GUI** [comment]
It was related to the [`.helm/secret-values.yaml` file](https://github.com/GUI/covid-vaccine-spotter/blob/main/.helm/secret-values.yaml) where I store encrypted versions of credentials used during deploys. It's not necessarily obvious from the format, but these values are encrypted (using [Werf secrets](https://werf.io/documentation/v1.2/advanced/helm/configuration/secrets.html)), so after discussing the encryption format Werf uses (it could perhaps be stronger, but it defaults to AES-CBC-128), this shouldn't be a problem as long as the encryption key stays secret. But I appreciate anyone raising potential security concerns!

**Comment by paf0186** [comment]
Ah, makes sense - Thank you!
