### ISSUE TITLE
request to add Rite-Aid vaccine types

### ISSUE THREAD

**Issue by kartiksubbarao** [GUI/covid-vaccine-spotter#132]
The mapping for Rite-Aid vaccine types is available in this JavaScript file:
https://www.riteaid.com/etc.clientlibs/riteaid-web/clientlibs/clientlib-base.js

PREF-113 => Moderna
PREF-114 => Pfizer
PREF-115 => Johnson & Johnson

**Comment by the-red-lily** [comment]
Thanks for the research you've already done. I'll look into this. Seems like a doable project for a first timer!

**Comment by JavierCoronaA01023063** [comment]
Can you please add by date!! I would appreciate this a lot!

**Comment by kartiksubbarao** [comment]
Thanks @the-red-lily. Just to provide some more info -- Rite-Aid provides the vaccine type at the storewide level, but it looks like the vaccinespotter code prefers to manage this on a per-appointment level (which other stores provide). vaccinespotter does provide an **appointment_vacine_types** dict at the store level in the JSON API, which could be populated for Rite-Aid. This dict is what I'm currently using in my monitoring script to check for particular vaccine types. In any case, if the data can be made available in some form or fashion, I think it would be useful.

**Comment by GUI** [comment]
Awesome, thank you for the tip! Vaccine type information for Rite Aid locations should now be showing up and filterable.

**Comment by kartiksubbarao** [comment]
Thanks @GUI!
