### ISSUE TITLE
Oops! We couldn't find that ZIP code in this state. Please double check it or try a different ZIP code. 

### ISSUE THREAD

**Issue by markspivey** [GUI/covid-vaccine-spotter#133]
We seem to be getting errors saying that valid ZIPs cannot be found in the state (IL). 

![image](https://user-images.githubusercontent.com/71787519/113948755-4109ff80-97d3-11eb-89f1-5a63178b1f22.png)

**Comment by dnyt84** [comment]
Same problem in Colorado, even if I pick a zip code that is listed for available appointments in the list.

**Comment by fumb1e** [comment]
Ditto for Oregon.

**Comment by arane4114** [comment]
Seen with IL, IN and IA

**Comment by brandonlou** [comment]
Same for CA

**Comment by brian163** [comment]
Same for NJ, so at this point, likely everywhere?

**Comment by brian163** [comment]
And... it appears to be working again.

**Comment by GUI** [comment]
Yeah, sorry about that all! I was shuffling some server-side things around, and unfortunately ran into some new issues on the live site I didn't find earlier (basically what was happening was some cached files were getting served up with the wrong compression, leading to un-parsable files). I believe this should be fixed now and any cached should be purged (https://github.com/GUI/covid-vaccine-spotter/commit/4b50911aa453ab43f9b7f5e07b9f2528617a6127). Pardon the interruption, but holler if anyone still sees any issues.
