### ISSUE TITLE
vaccinespotter.org: Fetching data...

### ISSUE THREAD

**Issue by jamespharvey20** [GUI/covid-vaccine-spotter#152]
I've tried up to date chromium and firefox, and the live website is getting stuck on "Fetching data..."

https://www.vaccinespotter.org/MI/?zip=48105&radius=25&appointment_type=&vaccine_type=pfizer&provider=

The Michigan json page loads fine for me:

https://www.vaccinespotter.org/api/v0/states/MI.json

**Comment by wmharrison** [comment]
Having same issue for MN, JSON also loads fine

**Comment by GUI** [comment]
Sorry! There were some server updates that went awry. I believe this should be fixed, but can you let me know if this is still occurring for you?

**Comment by jamespharvey20** [comment]
Yes, it's fixed!  Thank you so much for your work on this project.  It's literally already saved lives, and will continue to save many more.  Also thank you for what I think is the fastest response time I've ever seen on github!
