### ISSUE TITLE
Remove Health Mart Until Further Notice

### ISSUE THREAD

**Issue by sigmachirality** [GUI/covid-vaccine-spotter#154]
Health Mart's website cannot be trusted - they have pulled all vaccine appointments due to concerns over the side effects of the Johnson and Johnson vaccine.

**Comment by tsfischer** [comment]
J&J has been pulled nationwide... are you saying Healthmart is allowing you to schedule appointments but then not honoring them?

**Comment by jxchong** [comment]
yeah I don't think there's anything wrong with Health Mart's website other than some possible temporary hiccups for locations that only had J&J appts (presumably that's been handled by now). In WA, we have HM locations with availability for 2-dose vaccines and these are reporting correctly.

**Comment by GUI** [comment]
Yeah, I realize the J&J issues may have caused some bumps along the road the past week for several pharmacies, but I haven't heard of any continuing widespread issues, so I'm hoping most, if not all Health Mart locations being returned now are in fact bookable. So I'm going to close this, but thanks for bringing this up to let me know this was happening earlier. But let me know if anyone still hears of this issue happening.
