### ISSUE TITLE
Albertsons/Safeway scanning broken

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#16]
Around 4:30 today, the Albertsons scanning broke. As far as I can tell you now need to fill out the captcha before making any requests. They had added a captcha last week (I think), but the endpoints actually didn’t seem protected until today.

So far in trying to get this working again, I have code that can fill out the captcha (using a paid captcha service) in a headless browser, but the authenticated session is then only good for ~25 requests before the captcha is required again. So this could be rather slow and costly to support. I can push the captcha code up anyone’s interested, but I’m going to have to call it a night for today. I’ll see if I can figure anything out or find anyone at Albertsons to reach out to.

**Comment by renschler** [comment]
> I can push the captcha code up anyone’s interested

@GUI i'd be interested in seeing this! thanks for all your hard work on this project

**Comment by edcous** [comment]
Probably safe to close this now :)

**Comment by GUI** [comment]
Yup, with Albertons's revamping their site and finally allowing for scanning again (albeit, limited details), yeah, I think we can close this.
