### ISSUE TITLE
RiteAid false negatives (API has changed)

### ISSUE THREAD

**Issue by seanwlx** [GUI/covid-vaccine-spotter#174]
RiteAid is now showing availability by vaccine type.  The old indices in their api response array are no longer valid, and the current code is generating false negatives.

**Comment by GUI** [comment]
Thanks for the heads up! I believe this should be fixed now (by https://github.com/GUI/covid-vaccine-spotter/commit/b4aa5437a2e4fa315134f3344e1178fb97d820f4), but let me know if you're still seeing any issues.
