### ISSUE TITLE
Add Winn-Dixie Pharmacy

### ISSUE THREAD

**Issue by tinbromide** [GUI/covid-vaccine-spotter#23]
https://www.winndixie.com/pharmacy/covid-vaccine

When you click on the schedule appointment option, it takes you to a chat bot located on this site:

 https://c.ateb.com/c20605cb988e4a18a3eab5f7fd466cf6/?submit=Schedule+my+appointment

Once there, you can schedule a COVID 19 appointment in FL and it provides a list of locations with potential COVID-19 appointments.

**Comment by MoralCode** [comment]
after some initial poking around i have discovered that the chatbot works even if the page is downloaded and hosted locally (heres my copy, hosted with globally installed `jekylll serve`: 
[winndixiechatbot.zip](https://github.com/GUI/covid-vaccine-spotter/files/6127270/winndixiechatbot.zip))

This suggests that:
- cookies .etc shouldnt be an issue in terms of ratelimiting (other factors might be though)
- the actual API used for availability data is completely obscured behind the websocket chatbot


At the time of posting, crawfordville zip 32327 has available vaccine, if not, try looking on reddit for "vaccine winn dixie" to see if someone posted one of those "vaccine available now" posts recently that you can look up a zip code for

**Comment by GUI** [comment]
@MoralCode: Thanks! I think I've had some luck in the past couple days in figuring out their underlying WebSockets API, so I think I might have a path forward on this. I still need to do some more experimenting, but I'm hoping this might be one I can add soon.

**Comment by GUI** [comment]
Winn-Dixie is now added, along with some other Southeastern Grocers chains that share the same platform (Harveys and Fresco y Más).
