### ISSUE TITLE
Instructions for running locally?

### ISSUE THREAD

**Issue by craig-cogdill** [GUI/covid-vaccine-spotter#25]
I'd like to contribute if I can, but I can't find instructions on how to build/run this locally so I can test my changes. Any help would be appreciated.

**Comment by GUI** [comment]
@craig-cogdill: Sorry for the delay on this! If you're interested in tweaking the website, I've added some initial setup instructions here: https://github.com/GUI/covid-vaccine-spotter#development-setup If you were interested in the underlying data scanning and backend pieces, I still need to figure out a good bootstrapping process for that, so unfortunately I don't have full setup instructions for that yet.

**Comment by kaspar-p** [comment]
Commenting so that I get notifications if this gets updated. I'd like to contribute also!

**Comment by craig-cogdill** [comment]
Thanks for the instruction set @GUI. I added a PR for your review that scripts this initial setup: https://github.com/GUI/covid-vaccine-spotter/pull/41

**Comment by AnEmortalKid** [comment]
>  If you were interested in the underlying data scanning and backend pieces, I still need to figure out a good bootstrapping process for that 

i can try to mess with that. I think maybe a container with postgres and running all your migrations might work. I'll do some digging.

**Comment by craig-cogdill** [comment]
README has been updated with instructions for getting a dev environment off the ground. Closing.
