### ISSUE TITLE
Add Publix Pharmacy

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#31]
https://www.publix.com/covid-vaccine

**Comment by adamncsu** [comment]
They have an API URL for status: 
https://www.publix.com/covid-vaccine/florida/florida-county-status.txt?t=1614777630174
https://www.publix.com/covid-vaccine/georgia/georgia-county-status.txt?t=1614777630174
https://www.publix.com/covid-vaccine/south-carolina/south-carolina-county-status.txt?t=1614777630174

They append epoch timestamp to the end, but that's probably just to avoid cache.

From what I can gather, if you can book an appointment online for the county, it will return a percentage for that county. If it returns "Less than 1%" or "Fully Booked", then you can't book an appointment online.

**Comment by GUI** [comment]
Publix was added last week. https://github.com/GUI/covid-vaccine-spotter/commit/a5d91ddc0e162c41d3b9f8f7014df71b62161548
