### ISSUE TITLE
Support Kroger in states beyond CO

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#32]
This is difficult due to their anti-bot technology. I sort of have something working for CO, but it's finicky. It might be possible to scale this to other states, though.

**Comment by GUI** [comment]
This is now being done.

**Comment by petegordon** [comment]
Great Job! I'm going to change from our process to your API for Ohio. Thanks!  https://github.com/GUI/covid-vaccine-spotter/issues/79
