### ISSUE TITLE
Add Costco Pharmacy

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#39]
https://www.costco.com/covid-vaccine.html

**Comment by MoralCode** [comment]
was able to pull out the lines containing links to each store and state headings from the page you linked using this (ugly) regex, vscode's find-and-replace, and alt+enter to select all matches: `(<div class="col-xs-12 col-md-4 col-lg-2"><a href="http[:.-a-z0-9/?&_=" ><#]+| <p class="panel-title">[><a-zA-Z0-9 ="\/\-#]+ )`. i did need to do some more finding and replacing to get it into the clean csv but it got most of the rest of the junk stripped out


WIP - will update this comment as investigation continues


this `e_id` seems to be the same as `employeeId`

https://book-costcopharmacy.appointment-plus.com/book-appointment/get-rooms?clientMasterId=422977&clientId=2425&employeeId=5389&serviceId=119&pageNumber=1&itemsPerPage=9&keyword=&roomId=&_=1616466514421

**Comment by GUI** [comment]
Yeah, Costco's system is interesting, with all the different links and variations by state/location. But this should now be implemented in 249c2636cba7871e719bacc13f13ed252ef8239b. Thanks for the tips, @MoralCode!

**Comment by jxchong** [comment]
@GUI FYI, you're missing one in WA state, likely because the e_id is missing from the Costco webpage's master list.
It appears as `https://book-costcopharmacy.appointment-plus.com/d0m1slrg/` and we are able to scrape it with:

`https://book-costcopharmacy.appointment-plus.com/book-appointment/get-grid-hours?startTimestamp=START_MONTH+00%3A00%3A00&endTimestamp=NEXT_MONTH+00%3A00%3A00&limitNumberOfDaysWithOpenSlots=4&employeeId=7061&services%5B%5D=137&numberOfSpotsNeeded=1&isStoreHours=true&clientMasterId=425227&toTimeZone=false&fromTimeZone=132&_=1618008954060`

Also Costco's page has been having major uptime issues for us, so be prepared to code for a lot of unique error messages including status 200 that passes a plaintext failure message.

**Comment by GUI** [comment]
@jxchong: Thanks for the sanity check and tip! I was basing my original store list on the list of Costco pharmacies and then matching them with the results on their COVID listing page. But this WA location looks like an odd case that's not actually a Costco store or pharmacy location. I've been able to handle all of the other locations missing `e_id` by making a request to the `get-employees` endpoint once I have a client ID matching the location. That process has worked for all of the other locations on this page, but these steps seem to be failing for this location (I can't ever get it to return a client ID in the `get-clients` endpoint). But I see that you have the address listed as 1490 NW 11th Ave NW, Issaquah, WA 98027, so maybe I'll just hard-code all of this into my database and then have it start monitoring that way. I'll try to revisit this tomorrow, but thanks again for letting me know!

**Comment by jxchong** [comment]
I haven't spent time digging outside WA for obvious reasons but my understanding is that there might be a few other locations like this (though it sounds like you were able to retrieve the missing e_ids for those). Yeah, this is an off-site clinic run by a local Costco store.

**Comment by MoralCode** [comment]
@jxchong is the e_id not the `employeeId=7061` part from the longer URL you posted? I noticed in my testing that this `emplyeeId` field seemed to correspond with e_id or at least have the same format of a 4-digit number.

Also the CSV link from my post above is a publicly-editable google doc where I've been trying to compile links to all the costco locations I can find. if you would like to add your store that would be awesome!

**Comment by jxchong** [comment]
@MoralCode Yes I think e_id is the same as employeeId. I don't run the Costco scraper for our group (CovidWA.com) so I'm just passing on some data points :)
