### ISSUE TITLE
Switch to PostgreSQL for database storage

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#4]
The current usage of Cosmos DB was sort of an early experiment while I was trying to figure out what cloud offerings could best host everything for free. But with the tasks running in AWS Lambda and the database over in Azure, this is all a bit funky and could use some cleanup.

And nothing necessarily against Cosmos DB, but I'd personally be more productive in PostgreSQL, so now that this tool seems like it's useful and I'd like to do more things in the database, I'd be fine paying a bit for a PostgreSQL service where I'd be more comfortable/productive. And hopefully this would also make everything easier to setup and run for others (so there wouldn't be the odd dependencies split between cloud services).

**Comment by spdolan** [comment]
Hey @GUI, digging what you're doing with this project! How can I help?

**Comment by GUI** [comment]
Thanks for offering, @spdolan! This task is actually now complete. It was mostly done last week (sorry I had forgotten to update this ticket), but I had one remaining provider (Kroger) that still wasn't on Postgres. But as of yesterday, that is now done.
