### ISSUE TITLE
Add ability to search and filter by location

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#44]
This is increasingly a request I'm hearing from users. The current approach of dumping all the information in the state into one page obviously isn't too user friendly, particularly in states with lots of locations.

I've started work addressing this and hope to have some improvements on this front soon.

**Comment by GUI** [comment]
Still probably improvements that could be made, but I'm going to consider this one done.

**Comment by mhunigan-cap** [comment]
How do you search the API or filter by location? I couldn't find it in the documentation.
