### ISSUE TITLE
Improve UI navigation between different states

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#52]
If you land on a state-specific page, it may not be obvious that the site has data for other states. Technically you can click on the header in the navbar (eg, "Colorado COVID-19 Vaccine Spotter"), and you'll land back on the home page, but this is not obvious (or perhaps even the correct action for that title) at all.

Having some better type of global navigation might be useful. Or alternatively, maybe just some state drop down in the nabber to switch between states (although on mobile, this would probably need to be collapsed in a menu due to space).

**Comment by AshleyMSherwood** [comment]
Hi! I'm new to contributing to Open Source projects, but would love to help. I'm thinking this issue could be resolved simply by removing the link from the title ( {{stateName}} COVID-19 Vaccine Spotter ) and adding a link to the homepage on the left that says "View Other States."  Would this solve the issue?  I'd appreciate any feedback! Thanks.
<img width="1020" alt="vaccine-spotter-issue-52-fix" src="https://user-images.githubusercontent.com/9452459/111360209-78fda700-865a-11eb-9a40-96121d8dc4d5.png">

**Comment by GUI** [comment]
I've tried to address this with a new select menu in the navbar in https://github.com/GUI/covid-vaccine-spotter/commit/d91cd1ddb07d6b9413284508bbe7ca3784e2054f
