### ISSUE TITLE
Add filtering based on vaccine type

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#55]
This is tricky to do, since I'm not sure we have the data necessary to do this right now, but just noting a request I've heard. But if we can reliably normalize the data from pharmacy providers, I know some people are only looking for 1st or 2nd shots and then some people are looking for types of vaccines (eg, Moderna, Pfizer, J&J).

Right now I've started to keep track of the appointment "type" which does include some of this information, but this is usually just based on text we get back from the pharmacy, so it's not standardized across different pharmacies. And we also don't have this information for all chains (some we just have appointment times, and other we don't have any details).

**Comment by Mutmatt** [comment]
Looks like this has been completed via this commit https://github.com/GUI/covid-vaccine-spotter/commit/5e8efb7e715e9850bceb4cc69a33ebd82bd64953

**Comment by GUI** [comment]
Ah, yes, thanks for the reminder. :)
