### ISSUE TITLE
Add translations into other languages

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#56]
Could start out by adding something like Google Translate to the page, but if there's demand and interest, I'd certainly be open to properly localizing the tool for other languages.

**Comment by wsolorza** [comment]
[WeGlot is free ](https://weglot.com/github-students/)if you have the GitHub student pack

**Comment by lawrencek1992** [comment]
I can translate the site to Spanish if you want? I'm bilingual.

**Comment by racedale** [comment]
This seems like the way to go for adding i18n capabilities to Nuxt: https://i18n.nuxtjs.org/setup

**Comment by MoralCode** [comment]
Have many of the strings on the site already been pulled out into a dedicated file for translation? that might be a useful first-step that may be relatively beginner-friendly. Not super familiar with Nuxt but the plugin mentioned above may facilitate this?

**Comment by patrickdemers6** [comment]
@lawrencek1992 I'm getting started pulling all application text into a translation file. Would you be able to help me with some Spanish translations?

**Comment by lawrencek1992** [comment]
Yes, I can do that. How can I access your file? Bit new to Github. Sorry if
that's a basic question.

Kelly

**Comment by patrickdemers6** [comment]
Let me finish getting everything pulled out. Then, we can have you add the Spanish version of everything!

**Comment by lawrencek1992** [comment]
Sounds good! Keep me posted.

**Comment by patrickdemers6** [comment]
Alright, I have pulled nearly everything out. I'm struggling to get the Map Popup working. A sub Vue instance is created and doesn't have access to the i18n plugin. I'll keep working on that. I'll also work on making it so the user can select the language they would like.

In the meantime, I believe you should be able to fork my fork, add the translations in `website/language.js`, then create a PR to my branch.

**Comment by lawrencek1992** [comment]
Awesome I'll get started tonight! Doesn't look like a ton of text. Probably take me a day or so, depending on how much I can do tonight.

**Comment by MoralCode** [comment]
@patrickdemers6 does the plugin allow us to specify the language in the URL somehow? like `vaccinespotter.org/en` would link to the english one or set the language to `en-us` and  `vaccinespotter.org/es` would set it to spanish (not sure what the language code for that is, probably `es`?

**Comment by patrickdemers6** [comment]
I wasn't planning on doing it that way but it may not be a bad idea. @GUI would you like to include the locale in the url?

My current plan was to default to the user's browser preference and have an option to switch locales using a dropdown menu. I think this method would make SEO easier and prevent having any routing issues.

**Comment by patrickdemers6** [comment]
I lied, it is going to edit the url! I have it working pretty well in my fork's branch. Creating WIP PR now.

**Comment by MoralCode** [comment]
> I think this method would make SEO easier and prevent having any routing issues.

i think there is actually a way to tag links between versions of the page with different locales so search engines can parse it/see it: https://ahrefs.com/blog/hreflang-tags/

**Comment by lawrencek1992** [comment]
@patrickdemers6 I just made a pull request on your 56-translations branch with the updated file. I noted a couple of things that need to be changed (like changing the time to 24hr vs 12hr for Spanish speakers). Also noted that the button needed to change from "Spanish" to "Español." And then right after making the pull request, I noticed that you already made a commit with that change. So disregard that bit.

**Comment by wsolorza** [comment]
Is the Spanish version ready? Kelly you're a rock ⭐

**Comment by patrickdemers6** [comment]
@wsolorza Spanish version is ready! Just put #95 to ready. I ended up doing the last couple translations through Google Translate as the longer this is open the harder it is to merge. Just about every file is modified quite a bit.

**Comment by lawrencek1992** [comment]
I updated the news, should be good to go now. Can also help with updating news in the future if it or other text on the English site changes again. Thanks @wsolorza ! I'm really stoked to be able to share the site with friends and people at work who only speak Spanish. Other languages are important too, but Spanish gets a big net of people in the US, which is great.

**Comment by varnav** [comment]
I can do Russian, what are the steps?

**Comment by lawrencek1992** [comment]
I forked Patrick's repository and in the translations branch simply made a
spanish.js file (the naming structure may have changed) and translated the
English to Spanish. Like all the strings. He pulled them in there. You
could probably do the same for a Russian file.

**Comment by GUI** [comment]
Finally merged in with https://github.com/GUI/covid-vaccine-spotter/pull/95 Thank you everyone!

If anyone's interested in doing other languages, it can be based on https://github.com/GUI/covid-vaccine-spotter/blob/main/website/lang/es.json. I'll try to get a better workflow setup, but in the meantime, feel free to open a new issue about any new translations requested.

**Comment by GUI** [comment]
For anyone else that was interested in contributing language translations (in Spanish or in other languages), I hope to have setup a better workflow for this now. If you'd like to contribute translations, you can use the Localazy service to review missing translations, suggest tweaks, or add new languages: https://localazy.com/p/vaccinespotter. Thanks again for everyone's help in doing this, I've seen a decent amount of traffic to the new Spanish pages this week, so it seems like they're definitely getting used! Thank you!

**Comment by patrickdemers6** [comment]
@GUI That looks really useful. Hopefully it can be used to get some additional languages added to the site!
