### ISSUE TITLE
Some Walgreens locations you can't book despite claiming to have availability

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#61]
This has been heavily affecting at least Colorado users the past several days causing lots of frustration.

Basically the issue is that Walgreens' data will claim to have availability for a specific store. Even if you specifically select that you need "First & Second Dose" it will let you proceed with booking at locations that have appointments in the next several days. However, once you get the step to book the second dose, Walgreens will inform you that there is no availability and therefore you can't book anything.

Many CO users have reported that they've called the pharmacies and the pharmacies have said they are not currently doing any first & second doses in CO, only second doses. However, I know I've heard from some users that have still had success in booking first and second doses at Walgreens (however rare), while I've added warnings, I've been hesitant to yank the data entirely.

So while I sort of consider this an issue on Walgreen's end with providing misleading information on the initial requests until you get further into the process, this is something I'd like to address to prevent more frustration on the part of users. After digging into this, in order to fix this, we need to check for future booking dates to simulate what the Walgreens does when you go to book the 2nd dose. The logic Walgreens seems to use for looking for 2nd dose appointments is:

- Look for appointments starting 28 days ahead of the 1st dose time. This seems to happen regardless of vaccine time (Moderna of Pfizer).
- Each appointment slot API request fetches 3 days in the future of the first date, so there has to be some time slot bookable within that 28 + 3 day window from the original appointment date.

We should then only consider the 1st appointments valid if there's a 2nd dose appointment open in the future according to these rules.

**Comment by GUI** [comment]
This is mostly addressed by ef65eb533dc24ba22d3d34f160988b5839798d28. However those changes currently have the side effect of hiding appointments which might be bookable if you just need a 2nd dose. I want to hide these by default, since I think this is a rarer use case, but I'd like to bring those back in the UI in some fashion, since I know some people are just seeking 2nd appointments. But this change hopefully addresses the larger frustration felt by many users seeing Walgreens appointments as bookable, but not actually being able to book them.

This issue seems to have heavily affected CO, NV, PR, and RI, affecting nearly all of the stores showing availability in those states. However, it seems to have affected a handful of other stores in other random locations, so hopefully by checking for 2nd appointments everywhere, it will make things more reliable for everyone. Here's a tally of how many stores currently seem to be affected by this issue (having upcoming appointments in the next few days, but not being able to book a 2nd appointment):

|State|Count|
|-|-|
|CA|2|
|CO|40|
|CT|1|
|KY|1|
|LA|1|
|NC|1|
|NV|18|
|NY|6|
|PA|6|
|PR|27|
|RI|12|
|TX|1|

**Comment by rotywonka** [comment]
This is also happening in Pennsylvania. Rite-aid is another victim of this "bug".

**Comment by shott** [comment]
This also appears to be an issue with Walmart in Arizona. VaccineSpotter shows plenty of slots, but the Walmart scheduling app reports no availability …. Unless I’m being a complete idiot.

**Comment by shott** [comment]
Note: for Walmart in Arizona, I found that I could see and book appointments 90-120 minutes after vaccinespotter showed them. While I can explain that delay, it is a useful function to know that they should be available soon on the Walmart.com site.

**Comment by kheifer** [comment]
This is an error in their code and not one that I think can be fixed on this end.

**Comment by GUI** [comment]
This specific Walgreens issue was mostly addressed back in https://github.com/GUI/covid-vaccine-spotter/issues/61#issuecomment-796165617. I had been keeping this issue open due how the original changes hid any 2nd-dose only appointments. But with changes last week that allow for filtering based on 2nd dose only appointments, I think this can now be considered resolved.

Regarding any other issues with Walmart or Rite-Aid, I'll have to look into those separately. I know at times Rite-Aid has changed eligibility rules on their site in rather non-obvious ways, so that can sometimes cause issues (since there can be open appointments, but only if you fill out the form "right" for their custom eligibility rules). But if anyone has specific locations that are acting up, please file a new issue, and we can try to get the the bottom of it. Thanks all!
