### ISSUE TITLE
Make Steps smaller

### ISSUE THREAD

**Issue by patrickdemers6** [GUI/covid-vaccine-spotter#78]
The two steps that are displayed at the top of each state's page take up quite a bit of space, particularly on non-desktop screens. I do think having the details of using the tool is a useful feature. Instead of having them both be so big, could we move them to [Expansion Panels](https://material-ui.com/components/accordion/)? It could look something like what's below. This way, the user is able to expand and view more details if they are interested.

Collapsed:
![image](https://user-images.githubusercontent.com/12687723/111803713-4e4f6080-889d-11eb-9dd1-d226529be5c5.png)

Expanded:
![image](https://user-images.githubusercontent.com/12687723/111803764-5d361300-889d-11eb-865f-9b3a3e048e28.png)

**Comment by GUI** [comment]
Yeah, this has something that's been bothering me for a while, particularly with as many mobile users that are accessing the site. So thanks for filing this issue along with some ideas! I know I tend to be a bit too verbose with my wording, but nobody actually reads words. 😄 I like the idea of some type of collapsable setup. There's maybe some small things I'd like to try to highlight in the short versions (that this tool doesn't necessarily cover all your options), but I can think about how to word that succinctly. But in any case, I think this would be a great improvement to prevent so much of the important content from falling below the fold.

**Comment by patrickdemers6** [comment]
Awesome! I will get crackin' on it.

**Comment by GUI** [comment]
Hoping this is fixed by https://github.com/GUI/covid-vaccine-spotter/pull/166, but definitely let me know if you still have other thoughts on improve this. Thank you!
