### ISSUE TITLE
CVS appointments not showing up?

### ISSUE THREAD

**Issue by paf0186** [GUI/covid-vaccine-spotter#86]
I've been pulling the MN data from the JSON API, and I've noticed that no CVS appointments seem to show up in the data for at least the last three or four days, but the local MN vaccine hunters group has reported availability via the CVS website several times.  The CVS site also shows appointments are currently available (as of 11:17 AM central on 3/21) in Duluth, MN, and that isn't showing up on the site (or in the API).

So, I don't know if this is a nationwide issue, but at least in MN, CVS appointments don't seem to be getting picked up.

**Comment by MoralCode** [comment]
What does the bx at the bottom of the page say for CVS? when i go to the MN page i see this, indicating that CVS was recently updated. I'm not the maintainer but i feel like this might be useful to know

![Screenshot_20210322_185550](https://user-images.githubusercontent.com/17362949/112081025-3a775900-8b40-11eb-8cd5-4bcb89d67420.png)

I suppose its also possible for the "last updated" data to be showing the last time CVS was updated for ANY state, which might be a different bug.

**Comment by paf0186** [comment]
Ah, good question, I didn't specify that.  Yeah, the last updated is fine.  It's not a single point in time problem - it's been going for days, and the last updated is (every time I've looked) in the expected window of a few minutes max.

**Comment by jeffchenoweth** [comment]
This happens because CVS doesn’t always update their main page (https://www.cvs.com/immunizations/covid-19-vaccine?icid=cvs-home-hero1-link2-coronavirus-vaccine) when appointments show up in the scheduler.

**Comment by paf0186** [comment]
Jeff,

So you're saying the scripts rely on the landing page and don't scrape the API directly?  (Yes, I'm being lazy and not checking the code, sry)

**Comment by jeffchenoweth** [comment]
Vaccine spotter pulls its availability data from the CVS endpoint that describes whether appointments are “available” or “fully booked” in a city, state. It does not pull from the appointment scheduler. Whether you can find additional appointments depends on whether CVS keeps the endpoint in sync.

**Comment by MoralCode** [comment]
I just did some brief poking around the appointment scheduler and have a Postman export. it seems like their requests are more complex than other places (theres a substantial body and a lot of cookies. not sure which are necessary). i was able to get a 200 OK in postman and change the zip code and distance in the body without issues. Api key appears to be the same for all requests, including with deleted cookies, a new browser, and a different IP.

heres the postman collection export (may need to change to .json)
[CVS.postman_collection.json.txt](https://github.com/GUI/covid-vaccine-spotter/files/6199773/CVS.postman_collection.json.txt)

**Comment by GUI** [comment]
Well, I know I'm belated in chiming in here, but I'm going to close this in light of changing CVS to use their more official data feed: https://github.com/GUI/covid-vaccine-spotter/pull/172 According to CVS, this new data should align with the rest of their systems, so hopefully it will be more accurate. But thanks for bringing this up!
