### ISSUE TITLE
Walmart checking (at least in Illinois) appears to be broken

### ISSUE THREAD

**Issue by edcous** [GUI/covid-vaccine-spotter#96]
Title, was last checked an hour ago...

**Comment by edcous** [comment]
Appears to be fixed... closing now.

**Comment by GUI** [comment]
@edcous: It's been up and down today as I've been working on it, but I'm hoping it should finally be in a better spot. The Walmart login process was getting stuck in a recaptcha loop, but I'm hoping to have addressed that with the changes in https://github.com/GUI/covid-vaccine-spotter/commit/da75b7e9278194eeb3e260219df83d00b61fb693. But we'll see... 🤞 I really appreciate the heads up, though! Give a shout if you see any issues again.

**Comment by edcous** [comment]
Perfect, thanks!
