### ISSUE TITLE
Latest updates break page loads in IE11

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#97]
I've heard from one user that the latest filtering UI updates from last night break the loading of the state pages in IE11. IE11 represents a small portion of our traffic, but we may still consider fixing this (since I know some people are still stuck on this on work computers) or at least add a warning banner declaring that the site isn't compatible and to try a different browsers.

I think the site was perhaps somewhat broken before in IE11, but the server-side rendering may have at least let some results show up. But in any case, it's now throwing a syntax error in the javascript, so need to see if this is something simple, or something more involved.

**Comment by binaryLady** [comment]
The devs volunteering their time to build this tool should not be required to support obsolete browser IE11.

**Comment by GUI** [comment]
Ah, yeah, I added a warning to IE browsers that should better clarify the site is no longer compatible, so I'm going to consider this resolved.
